"""add location to barber and telegram id to user

Revision ID: 5313ca3950f6
Revises: 35f47cfb82f7
Create Date: 2026-05-06 19:02:29.876832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5313ca3950f6'
down_revision: Union[str, Sequence[str], None] = '35f47cfb82f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barbers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('barbers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('barbers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('barbers', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('barbers', 'telegram_chat_id')
    op.drop_column('barbers', 'address')
    op.drop_column('barbers', 'longitude')
    op.drop_column('barbers', 'latitude')
    # ### end Alembic commands ###
